version: "3.7"
 
services: 
  flask:
    build: ./flaska
    container_name: skhswaggerflask
    image: skhswaggerflask:0.1.0
    restart: always
    environment:
      - APP_NAME=FlaskApp
    expose:
        - 5000
    #ports:    
    
  nginx:
    build: ./nginxd
    container_name: skhswaggerflask_nginx
    image: skhswaggerflask:1.0.0
    restart: always
    ports:
      - "8800:8800"
      #- "443:443" 
    depends_on:
      - flask
      
  #db:
    #image: postgres
    #container_name: postgres
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    #environment:
    #  POSTGRES_DB: db_name
    #  POSTGRES_USER: postgres_n
    #  POSTGRES_PASSWORD: postgres_p
    #ports:
    #  - 5432:5432